# Generated by Django 2.2.17 on 2021-01-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210111_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='profile_user',
        ),
    ]
