# Generated by Django 2.2.17 on 2021-01-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210113_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, default='You can contact with me in mail. My mail you can see in down', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default_profile.png', upload_to='images/'),
        ),
    ]
