# Generated by Django 2.2.17 on 2021-01-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210118_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, default='You can contact me through my mail.', max_length=100),
        ),
    ]
